name: generate-snake

on:
  schedule:
    - cron: "0 */12 * * *"   # günde 2 kez
  workflow_dispatch:          # elle çalıştırmak için
  push:
    branches: ["main"]        # (opsiyonel) main'e push olunca çalışsın

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: GkyEla       # <-- BURAYA KENDİ ADINI YAZ
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
